// The token bucket in model.ts paces against the provider's real TPM. These
// tests inject a fake fetch, so the limit is raised here — pacing is exercised
// by its own unit tests, not endured by every suite that makes a model call.
process.env.REVIEW_AI_TPM = "100000000";

import assert from "node:assert/strict";
import { describe, test } from "node:test";

import { ModelBudget } from "../dist/model.js";
import { checkMethodology } from "../dist/methodology.js";

// D3 is the most subjective check, so its guards matter most. Two of them are
// structural rather than promptable: it does not run without real sections to
// review, and a gap whose dependent claim cannot be quoted is dropped.

const PAPER = `Introduction
We present a retrieval system for glossary checking.

III. METHODS
We fine-tuned a classifier on the glossary corpus using a multilayer perceptron with two hidden layers.
Training used the Adam optimiser at a learning rate of 0.001 across five epochs on the available data.
Each entry was embedded with a multilingual sentence encoder producing seven hundred and sixty eight dimensions.
Negative examples were generated by substituting a randomly chosen translation from another entry in the corpus.
The corpus was split by concept so that a term and all of its translations fall on the same side of the split.
Oversampling was applied to the training partition only, after the split had been performed.

IV. RESULTS
The system reached 99.13% accuracy on the held-out split, which shows the approach is ready for deployment in production settings.
We report macro F1 of 0.9902 across the same split, computed over the two classes present in the data.
Retrieval was evaluated separately and returned the expected entry at rank one for every query we issued.
Calibration was applied afterwards so that the reported confidences track observed correctness more closely.`;

const scripted = (body) => async () =>
  new Response(JSON.stringify({ choices: [{ message: { content: JSON.stringify(body) } }], usage: {} }), {
    status: 200,
  });

describe("D3 — it does not run without something to review", () => {
  test("a document with no methods or results section is skipped, not guessed at", async () => {
    // Plain unstructured text is the common case.
    // Inferring where an unlabelled document's methods end and then judging it
    // for what that guess omits would be a fabrication.
    let called = false;
    const { stats } = await checkMethodology("Just some prose about governance with no headings anywhere.", {
      budget: new ModelBudget(),
      modelOptions: {
        apiKey: "gsk_test",
        fetchImpl: async () => {
          called = true;
          return new Response("{}", { status: 200 });
        },
      },
    });
    assert.equal(stats.ran, false);
    assert.match(stats.skipped_reason, /no methods or results/);
    assert.equal(called, false, "no sections, no call, no cost");
  });

  test("a methods section too short to review is skipped", async () => {
    const { stats } = await checkMethodology("III. METHODS\nWe did a thing.", {
      budget: new ModelBudget(),
      modelOptions: { apiKey: "gsk_test", fetchImpl: scripted({ gaps: [] }) },
    });
    assert.equal(stats.ran, false);
    assert.match(stats.skipped_reason, /too short/);
  });

  test("a real methods+results paper IS reviewed", async () => {
    const { stats } = await checkMethodology(PAPER, {
      budget: new ModelBudget(),
      modelOptions: { apiKey: "gsk_test", fetchImpl: scripted({ gaps: [] }) },
    });
    assert.equal(stats.ran, true);
    assert.equal(stats.skipped_reason, null);
  });
});

describe("D3 — absence is anchored to a claim that depends on it", () => {
  test("an empty gaps list is the expected answer for a competent paper", async () => {
    const { findings } = await checkMethodology(PAPER, {
      budget: new ModelBudget(),
      modelOptions: { apiKey: "gsk_test", fetchImpl: scripted({ gaps: [] }) },
    });
    assert.equal(findings.length, 0);
  });

  test("a gap anchored to a REAL sentence survives", async () => {
    const { findings, stats } = await checkMethodology(PAPER, {
      budget: new ModelBudget(),
      modelOptions: {
        apiKey: "gsk_test",
        fetchImpl: scripted({
          gaps: [
            {
              item: "baseline",
              dependent_claim_quote:
                "The system reached 99.13% accuracy on the held-out split, which shows the approach is ready for deployment",
              reason: "No comparison point is reported for this figure.",
            },
          ],
        }),
      },
    });
    assert.equal(stats.reported, 1);
    assert.equal(findings.length, 1);
    assert.equal(findings[0].item, "baseline");
    assert.ok(findings[0].quote.includes("99.13%"));
  });

  test("a gap whose dependent claim is FABRICATED is dropped", async () => {
    // "No baseline is reported" is unfalsifiable hand-waving unless it is
    // anchored to a sentence that actually exists in the paper.
    const { findings, stats } = await checkMethodology(PAPER, {
      budget: new ModelBudget(),
      modelOptions: {
        apiKey: "gsk_test",
        fetchImpl: scripted({
          gaps: [
            {
              item: "baseline",
              dependent_claim_quote: "we outperform every prior system by a wide margin on all benchmarks",
              reason: "invented",
            },
          ],
        }),
      },
    });
    assert.equal(stats.reported, 1);
    assert.equal(stats.dropped_ungrounded, 1);
    assert.equal(findings.length, 0);
  });

  test("a fragment too short to be a claim is not an anchor", async () => {
    const { findings } = await checkMethodology(PAPER, {
      budget: new ModelBudget(),
      modelOptions: {
        apiKey: "gsk_test",
        fetchImpl: scripted({
          gaps: [{ item: "limitations", dependent_claim_quote: "accuracy", reason: "too short" }],
        }),
      },
    });
    assert.equal(findings.length, 0);
  });

  test("a model error is silence", async () => {
    const { findings, stats } = await checkMethodology(PAPER, {
      budget: new ModelBudget(),
      modelOptions: { apiKey: "gsk_test", fetchImpl: async () => new Response("", { status: 500 }) },
    });
    assert.equal(findings.length, 0);
    assert.equal(stats.errors, 1);
  });
});
